# Generated by Django 5.2.12 on 2026-03-23 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nome_tipo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('data_evento', models.CharField(max_length=255, null=True)),
                ('nome_evento', models.CharField(max_length=255)),
                ('id_tipo', models.ForeignKey(db_column='id_tipo', on_delete=django.db.models.deletion.DO_NOTHING, to='calendarioApp.tipo')),
            ],
        ),
    ]
